### ISSUE TITLE
[Feature Request] More script types

### ISSUE THREAD

**Issue by Level0gamedev** [sarahgould/mosi#1]
First of all, really like mosi and I hope it will be developed more. Now that I have some free time I will start adding feature requests here :)

Currently there is only "say" script. To make mosi accessible, I can see other script types being blocks that you can add (instead of injecting code into dialogue). The blocks can be organized like code (so top one fires first) 
The scripts I would like to see are:

-  **DO**: This is a big one that I would like to see. It would allow for changing attributes of other sprites. So this could be used to open doors or move a guard out of the way etc. This could be done by allowing removing sprites and adding sprites to a map, so a door1 (closed) becomes a door2 (open) or guard1 is removed from x,y and put on x,y-2. It would be also cool if we could change color palette, enabling, disabling wall, this kind of stuff. We could do that easily by allowing naming of spawned sprites, or by letting a player choose a sprite by clicking on it.
-  **IF/ELSE** - this would be followed by a condition of checking a var. You can move other code blocks under it. 
-  **GO** (working like stepping on exit in Bitsy)
-  Create or update variable. Would be awesome if we could also create string variables
-  Play sound (for adding music, sfx)
- also implementing bitsy like say list or shuffle would be nice.

**Comment by sarahgould** [comment]
I am actually neck deep in a big refactor, one of the big reasons being... I want to support more scripts! A few of the ones you mentioned will supported in the next release, and a bunch more in future releases. (Though sounds is going to be hard because WebAudio support is a mess right now.)

**Comment by Level0gamedev** [comment]
Awesome, can't wait to see the new version!
Audio would be nice, but not super crucial. 

Would you rather have me to wait until the new version before submitting more feature requests?

**Comment by sarahgould** [comment]
Feel free to keep requesting things if you're inspired! It's great to hear feedback.

**Comment by hacknorris-aka-penguin** [comment]
i would add a string comparison and logic gates (or, xor, and, nand, not, nor...)
AND functions for getting list of items in one place when transparent sprites are on (for example its not possible to get if player is in air to transform it into ufo or smth...)

**Comment by hacknorris-aka-penguin** [comment]
and also lists ofcourse... not only variables...

**Comment by hacknorris-aka-penguin** [comment]
@zenzoa ;p

**Comment by hacknorris-aka-penguin** [comment]
okeh -w-
