### ISSUE TITLE
[Feature Request] Varied width font support

### ISSUE THREAD

**Issue by Level0gamedev** [sarahgould/mosi#13]
Add support for pixel fonts that are not monospaced (e.g. [here](http://www.squaregear.net/fonts/tiny.shtml) i is only 2 pixels wide (one of the letter, one of white space) while w is 6 pixels wide (5+1 white space) )

This can be achieved by letting the engine parse each letter individually and assigning each individual width (as height should be constant, but enabling varied lead to some interesting things.). 

To enable the individual parsing the SIZE attribute of .bitsyfont can be changed to 0 0 instead of actual size, or just left blank.

**Comment by sarahgould** [comment]
This is actually supported in bitsy now (see the arabic font), so I'm adding support for this .bitsyfont feature in the next big release.

**Comment by sarahgould** [comment]
...and the new release is here! (on github anyway)
