### ISSUE TITLE
[Feature Request] Export game html at double resolution for smaller text.

### ISSUE THREAD

**Issue by Level0gamedev** [sarahgould/mosi#14]
Currently the text can get pretty big at 8x8 resolution as it is rendered at the same pixel size as everything else. A quick fix for text heavy games could be exporting the game at 16x16 resolution - making all the gfx scale 2x and render the text at now native resolution (making 1px of text being 2x smaller than 1px of sprites - similar to bitsy). 

Making the text smaller only after export seems like the easiest approach to me.

**Comment by sarahgould** [comment]
I'm not sure I agree that this is the right solution, but I do think I want to provide better support for other languages and writing systems that might need a higher resolution. One way to do this would be to render the text as a separate layer on top of the main game, which would allow it to be a different resolution entirely, but I'm still investigating possibilities.
