### ISSUE TITLE
Export doesn’t export new color palettes, iOS

### ISSUE THREAD

**Issue by birdstare** [sarahgould/mosi#16]
I made a new color palette and applied it to 3 rooms. This color palette isn’t applied in the export. I tried deleting the default palette to see if I could replace the palette but I have just broken everything in doing this. I probably shouldn’t delete default things :/. Now I can’t draw anything in the room view.

**Comment by sarahgould** [comment]
I'll look into this asap. If you send me your export I can fix it manually for now!

**Comment by birdstare** [comment]
[oracle2.zip](https://github.com/sarahgould/mosi/files/2717383/oracle2.zip)
Here's the export!

**Comment by sarahgould** [comment]
I think I have it fixed now!
