### ISSUE TITLE
[Feature Request] Choose color by hex code

### ISSUE THREAD

**Issue by Level0gamedev** [sarahgould/mosi#2]
Having the color wheel is nice, but to make the engine really usable user should be able to choose color by hexcode as well.

**Comment by sarahgould** [comment]
The color editor actually already has a text box to edit the hex code. It may be getting cut off at the bottom of the panel though, I'm trying to improve the responsiveness of the editor.

**Comment by Level0gamedev** [comment]
Yep, found it by zooming out the webpage. Because on 100% zoom it looks like this:
![image](https://user-images.githubusercontent.com/20285394/49700310-fb10e280-fbaa-11e8-86b4-f72972612258.png)
