### ISSUE TITLE
Unable to access mosi

### ISSUE THREAD

**Issue by Godatplay** [sarahgould/mosi#21]
![image](https://user-images.githubusercontent.com/198019/55909804-7fe42b00-5ba2-11e9-87b9-c5c009859842.png)

I'm unable to use mosi because clicking "got it" doesn't seem to do anything. I've tried restarting and clearing cookies, but I seem to be stuck. You can see in the BG that it seems to only load some of the room thumbnails. The only thing that works is using it in a different browser.

Any other ideas?

**Comment by sarahgould** [comment]
I'm guessing there's a javascript error. Can you take a screenshot of the browser console? (Here's how to open it: https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers)

**Comment by sarahgould** [comment]
You can also recover your world data from the console by using this command:
`localStorage.getItem('world')`
It will output a really long string, which you can copy and paste into a text file as a backup. It may be that mosi saved some bad data, and I'll need to fix it by hand, but you won't be losing any of your work!

**Comment by Godatplay** [comment]
`TypeError: sprite is undefined` in room.js line 194

I've been saving my data, so it's not lost, no worries there. I guess it was a cache issue, not a cookie issue, so clearing cache for the mosi site fixed it.
