### ISSUE TITLE
Browser Window Scrolls When Controlling the Game

### ISSUE THREAD

**Issue by Limisios** [sarahgould/mosi#22]
I uploaded my game to [itch.io](https://limisios.itch.io/old-world) but when I use the up and down arrow keys to control the game, it scrolls the browser page up and down along with the game.

**System information**
MacOS 10.14.4
Firefox 66.0.3 (64-bit) + Safari 12.1

**Comment by sarahgould** [comment]
Just pushed a fix for this! I'll update the itch.io version shortly. (You'll need to export your game again, but you want to wait until I take a look at your other bug.)
