### ISSUE TITLE
Default Bitsy font scaling issue

### ISSUE THREAD

**Issue by Godatplay** [sarahgould/mosi#25]
I'd like to use a font that is 2x resolution of the in-game graphics, just like Bitsy does. So I figured I'd use the default Bitsy font. But it seems to get scaled in a weird way when I use it:
![image](https://user-images.githubusercontent.com/198019/56226108-3aa77980-6038-11e9-9418-a29c945557a3.png)

**Comment by Godatplay** [comment]
This seems to be limited to previewing in the editor

**Comment by sarahgould** [comment]
Need to add the preview again to the new version, but uh, technically this bug is solved by not having the text preview. I'll add that back soon!
