### ISSUE TITLE
Discrete avatar movement

### ISSUE THREAD

**Issue by Godatplay** [sarahgould/mosi#26]
It would be great to have a built-in option to make the avatar movement discrete. I find it much more aesthetically consistent that way. Once that is changed, it becomes clear the key repeating is quite frequent; I thought setting the repeat rate to the framerate might be a good alternative. I've made sure to keep moving at whatever desired rate based on repeated presses.

I've modified my code and I like how it feels. I thought others might like it this way as well.

**Comment by sarahgould** [comment]
I'm going to be using discrete avatar movement in the next big release.

**Comment by sarahgould** [comment]
...and the new release is here! (on github anyway)
