### ISSUE TITLE
Were settings removed?

### ISSUE THREAD

**Issue by Godatplay** [sarahgould/mosi#29]
Were games settings removed from the new version? Such as changing the resolution of various things. I couldn't seem to find them anywhere.

**Comment by sarahgould** [comment]
They’re available when you make a new world - since it would overwrite stuff anyway when you changed resolutions that seemed a logical place for those settings.

**Comment by Godatplay** [comment]
Ahhh gotcha, thanks! Would be helpful to see that in the wiki at some point ^_^
