### ISSUE TITLE
[Feature Request] Expanded Color Handling

### ISSUE THREAD

**Issue by Level0gamedev** [sarahgould/mosi#3]
One thing that I really miss in Bitsy is choosing both the 0 and 1 colors for each tile (just like in tiled graphics in microcomputers of the 80s, like Commodore64 or ZX spectrum).

Right now the user chooses color 1, and color 0 stays transparent. This is great for default behavior, but it would open a lot more possibilities if the user could also choose the background color. Alternatively, this can be achieved by allowing sprites to sit on top of one another, like in transparent sprites bitsy hack.

Also, it would be great if we could choose or hack in more than 3 colors, similar to bitsy. I think having up 8 colors would be amazing.

Edit: Attached an ZX spectrum example of the difference between the color0 / bg being constant, and being able to change it.
![viator-spider](https://user-images.githubusercontent.com/20285394/49699959-e4b45800-fba5-11e8-90f3-0ba42357ca9b.png)

**Comment by sarahgould** [comment]
I've got you covered! You can stack sprites in the room editor already - just try drawing them on top of each other. (I'm going to be trying out a slightly different room editor interface in the next version, but you'll still be able to enable stackable sprites in the settings.)
