### ISSUE TITLE
LMB does not stack tiles

### ISSUE THREAD

**Issue by Level0gamedev** [sarahgould/mosi#6]
When placing tile, clicking left mouse button does not place a tile on top of existing tile. This is on the current Chrome, Windows10.
Clicking right mouse places the tile without an issue, but brings up the RMB menu. 
Not sure if this is a bug or a feature ;)

I would recommend modifying clicks with keyboard (not sure how to handle on mobile, maybe multitouch or extra icons?). The way I would see it is:

- Shift + LMB - Add a tile on top of existing tile.
- Alt + LMB - choose a tile (like bitsy). After clicking this the clicked tile would become active. If there are multiple tiles in the same space, multiple clicks would cycle through the chosen tile.
- Crtl + LMB - delete a tile. Delete the top most tile. If there are multiple tiles in the space, it will delete the top tile. User needs to click again to delete any remaining tiles one by one.

**Comment by sarahgould** [comment]
Going to close this because I changed the way tile placement works. Let me know if there are issues with the new version, though (you can enable stacking the settings menu, and then drag tiles onto each other in the room editor).
